const CORE=30,MAX=5;let pHP=10,eHP=10,hand=[],sel=[],op='+',time=20,timer=null,locked=false;const enemyEmoji=['👾','🐲','👹','🤖','🦖','🐙'];
const $=id=>document.getElementById(id);function rand(n){return Math.floor(Math.random()*n)}function draw(n){while(n--){hand.push(rand(21))}}function render(){ $('ph').textContent=pHP;$('eh').textContent=eHP;$('tm').textContent=time;$('enemy').textContent=enemyEmoji[rand(enemyEmoji.length)];let h=$('hand');h.innerHTML='';hand.forEach((v,i)=>{let b=document.createElement('button');b.className='card'+(sel.includes(i)?' selected':'');b.textContent=v;b.onclick=()=>toggle(i);h.appendChild(b)});$('sel').textContent=sel.length?`選択中：${sel.map(i=>hand[i]).join(' , ')}　${op}`:'数字カードを2枚以上選ぼう';$('val').textContent='---';$('near').textContent='';}
function toggle(i){if(locked)return;if(sel.includes(i))sel=sel.filter(x=>x!==i);else if(sel.length<4)sel.push(i);calcPreview()}
function calc(){if(sel.length<2)return null;let a=hand[sel[0]],b=hand[sel[1]];if(sel.length>2)return null;switch(op){case '+':return a+b;case '-':return a-b;case '*':return a*b;case '/':return b!==0&&a%b===0?a/b:null}}
function calcPreview(){let v=calc();$('val').textContent=v??'---';if(v==null)$('near').textContent='';else $('near').textContent=v===CORE?'JUST！🎯':`COREまで ${Math.abs(CORE-v)}${v<CORE?' 小さい':' 大きい'}`}
document.querySelectorAll('.ops button').forEach(b=>b.onclick=()=>{op=b.textContent==='＋'?'+':b.textContent==='−'?'-':b.textContent==='×'?'*':'/';document.querySelectorAll('.ops button').forEach(x=>x.classList.remove('active'));b.classList.add('active');calcPreview()});
function range(v){if(v>=20&&v<=24)return ['🛡️ 防御',0];if(v>=25&&v<=29)return ['⚔️ 攻撃',1];if(v===CORE)return ['🎯 JUST',2];if(v>=31&&v<=35)return ['💥 強攻撃',2];if(v>=36&&v<=40)return ['✨ 特殊',3];return null}
function execute(){if(locked||sel.length<2){$('msg').textContent='数字を2枚選んでね！';return}let v=calc(),r=range(v);if(!r){$('msg').textContent='コマンドの範囲に入っていないよ。';return}locked=true;clearInterval(timer);let just=v===CORE;$('msg').textContent=`${v} → ${r[0]}${just?'　JUST！🎯':''}`;if(r[1]===0){$('msg').textContent+=' 次の攻撃を1軽減！';window.shield=just?2:1}else if(r[1]===1){eHP-=just?2:1}else if(r[1]===2){eHP-=just?3:2}else if(r[1]===3){pHP=Math.min(10,pHP+(just?3:2))}hand=hand.filter((_,i)=>!sel.includes(i));sel=[];draw(MAX-hand.length);render();$('msg').textContent=`${v} → ${r[0]}${just?'　JUST！🎯':''}`;if(eHP<=0){getChance();return}setTimeout(cpuTurn,900)}
function cpuTurn(){if(pHP<=0)return;locked=true;$('cpu').textContent='CPU「数字を考えている…」';setTimeout(()=>{let nums=Array.from({length:5},()=>rand(21)),best=null;for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){let a=nums[i],b=nums[j];[['＋',a+b],['−',a-b],['−',b-a],['×',a*b],['÷',a&&b%a===0?b/a:null],['÷',b&&a%b===0?a/b:null]].forEach(x=>{if(x[1]!=null&&range(x[1])){let score=Math.abs(x[1]-CORE);if(!best||score<best.score)best={a,b,op:x[0],v:x[1],score}}})}best??={a:nums[0],b:nums[1],op:'＋',v:nums[0]+nums[1],score:999};let r=range(best.v);$('cpu').innerHTML=`CPUは <b>${best.a} ${best.op} ${best.b} = ${best.v}</b> を選んだ！<br><b>${r?r[0]:'何もできない'}</b>${best.v===CORE?' 🎯 JUST！':''}`;if(r){if(r[1]===0)window.cpuShield=best.v===CORE?2:1;else if(r[1]===1)pHP-=best.v===CORE?2:1;else if(r[1]===2)pHP-=best.v===CORE?3:2;else pHP=Math.min(10,pHP+(best.v===CORE?3:2))}render();if(pHP<=0){$('msg').textContent='💥 YOU LOSE…';return}locked=false;startTimer()},800)}
function startTimer(){clearInterval(timer);time=20;render();timer=setInterval(()=>{time--;render();if(time<=0){clearInterval(timer);locked=true;$('msg').textContent='⏰ 時間切れ！ ターン終了';setTimeout(cpuTurn,700)}},1000)}
function getChance(){locked=true;$('modalTitle').textContent='🎉 ゲットチャンス！';$('modalText').textContent=`${$('enemy').textContent} が弱っている！\nもう一度、CORE NUMBER「${CORE}」をJUSTで作ろう！\nピッタリならGET！ ダメなら逃げられる！`;$('modal').classList.remove('hidden');$('modalBtn').onclick=()=>{ $('modal').classList.add('hidden');locked=false;time=20;sel=[];draw(2);render();$('msg').textContent='ゲットチャンス！ 30 JUSTを狙え！';startCaptureTimer()}}
function startCaptureTimer(){clearInterval(timer);time=15;render();timer=setInterval(()=>{time--;render();if(time<=0){clearInterval(timer);capture(false)}},1000)}function capture(ok){locked=true;if(ok){$('msg').textContent='🎊 GET！ モンスターをなかまにした！'}else $('msg').textContent='💨 逃げられた…';$('go').disabled=true}
$('go').onclick=()=>{if($('modal').classList.contains('hidden'))execute()};$('modal').innerHTML='<div class="modal-card"><div id="modalTitle"></div><div id="modalText"></div><button id="modalBtn">OK</button></div>';draw(5);render();startTimer();