const MAX_HP=10,HAND_SIZE=5,MAX_CARDS_PER_MOVE=3,TURN_TIME=20,CATCH_TIME=15;
const CORES=[20,30,50,100];
let CORE=30;
const MONSTERS=[
 {name:'ぷるんスライム',core:20,personality:'かんたん',abilityName:'ぷるぷるガード',ability:'guard',ops:['+','-'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/purun-little-magic-slime.webp'},
 {name:'こもりんバット',core:30,personality:'ふつう',abilityName:'JUSTハンター',ability:'just',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/komorin-little-night-bat.webp'},
 {name:'もふウルフ',core:50,personality:'てんさい',abilityName:'ブレス',ability:'breath',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/mofu-wolf-frost-pup.webp'},
 {name:'プリズムテールドレイク',core:100,personality:'てんさい',abilityName:'コアイーター',ability:'eater',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/prism-tail-drake.webp'}
];
const FANTASY_CHARACTERS=[
 {name:'かい・魔導士',id:'kai',stand:'kai-mage.png',attack:'kai-mage-attack.png',special:'kai-mage-special.png'},
 {name:'そら・剣士',id:'sora',stand:'sora-swordsman.png',attack:'sora-swordsman-attack.png',special:'sora-swordsman-special.png'},
 {name:'りく・忍者',id:'riku',stand:'riku-ninja.png',attack:'riku-ninja-attack.png',special:'riku-ninja-special.png'},
 {name:'つき・アーチャー',id:'tsuki',stand:'tsuki-archer.png',attack:'tsuki-archer-attack.png',special:'tsuki-archer-special.png'},
 {name:'なみ・守護騎士',id:'nami',stand:'nami-guardian-knight.png',attack:'nami-knight-attack.png',special:'nami-knight-special.png'},
 {name:'さく・僧侶',id:'saku',stand:'saku-cleric-healer.png',attack:'saku-cleric-attack.png',special:'saku-cleric-special.png'}
];
const ASSET_BASE='https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/';
const BACKGROUNDS=['forest.webp','cave.webp','ruins.webp'].map(x=>ASSET_BASE+'fantasy/backgrounds/'+x);
let state,timerId;
const $=id=>document.getElementById(id);
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function monsterForCore(core){return MONSTERS.find(m=>m.core===core)||MONSTERS[1]}
function getRanges(){const c=CORE;return[
 {min:c-10,max:c-7,name:'防御',icon:'🛡️'},
 {min:c-6,max:c-4,name:'攻撃',icon:'⚔️'},
 {min:c-3,max:c-1,name:'強攻撃',icon:'💥'},
 {min:c,max:c,name:'JUST',icon:'🌟',just:true},
 {min:c+1,max:c+3,name:'強攻撃',icon:'💥'},
 {min:c+4,max:c+6,name:'攻撃',icon:'⚔️'},
 {min:c+7,max:c+10,name:'回復',icon:'💚'}
]}
function makeDeck(){const c=[];for(let n=1;n<=20;n++)for(let i=0;i<2;i++)c.push(n);return shuffle(c)}
function getCollection(){try{return JSON.parse(localStorage.getItem('numberCoreMonsters')||'[]')}catch{return[]}}
function addMonster(mon){const a=getCollection();if(!a.includes(mon.name)){a.push(mon.name);localStorage.setItem('numberCoreMonsters',JSON.stringify(a))}}
function getDiscovery(){try{return JSON.parse(localStorage.getItem('numberCoreDiscovery')||'[]')}catch{return[]}}
function rememberMethod(c){if(!c)return;const key=`${c.nums.join(',')}|${c.ops.join(',')}|${c.value}`;const a=getDiscovery();if(!a.some(x=>x.key===key)){a.push({key,nums:c.nums,ops:c.ops,value:c.value,core:CORE,at:Date.now()});localStorage.setItem('numberCoreDiscovery',JSON.stringify(a))}}
function formatFormula(c){if(!c)return'';let s=String(c.nums[0]);for(let i=0;i<c.ops.length;i++)s+=` ${c.ops[i]} ${c.nums[i+1]}`;return`${s} ＝ ${c.value}`}
function ensureEnhancementUI(){
 const calc=document.querySelector('.calculator'),battle=document.querySelector('.battle');
 if(calc&&!$('strategyPanel')){const d=document.createElement('div');d.id='strategyPanel';d.className='strategy-panel';d.innerHTML='<div class="section-title">今回の作戦</div><div class="strategy-buttons"><button data-strategy="just">🌟 JUSTをねらう</button><button data-strategy="near">🎯 できるだけ近づく</button><button data-strategy="safe">🛡️ 安全に戦う</button></div><div id="strategyText" class="strategy-text">作戦を選ぶと、数字の見方が変わります。</div>';calc.insertBefore(d,calc.querySelector('.expression'));d.querySelectorAll('[data-strategy]').forEach(b=>b.onclick=()=>{state.strategy=b.dataset.strategy;render();status(strategyText())})}
 if(battle&&!$('comboHud')){const d=document.createElement('div');d.id='comboHud';d.className='combo-hud';d.innerHTML='<span>COMBO</span><b id="comboCount">0</b><small id="powerState">CORE POWER 準備中</small>';battle.appendChild(d)}
 if(!document.body.dataset.enhanced){document.body.dataset.enhanced='1';const observer=new MutationObserver(()=>{if(state)syncEnhancements()});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['src']})}
 syncEnhancements()
}
function strategyText(){return state.strategy==='just'?'JUSTを作れる組み合わせを優先しよう。':state.strategy==='near'?`${CORE}との差を小さくする組み合わせを探そう。`:'まずは防御・攻撃で安定して戦おう。'}
function syncEnhancements(){if(!state)return;const d=$('discoveryCount');if(d)d.textContent=getDiscovery().length;const c=$('comboCount');if(c)c.textContent=state.combo||0;const p=$('powerState');if(p)p.textContent=state.corePower?'⚡ CORE POWER READY':'CORE POWER '+(state.combo>=3?'チャージ中':'準備中');const st=$('strategyText');if(st)st.textContent=strategyText();const m=state.monster;if(m){const side=$('enemyNameSide');if(side)side.textContent=m.name;const core=$('enemyCoreSide');if(core)core.textContent=CORE;const per=$('cpuPersonality');if(per)per.textContent=m.personality;const ability=$('enemyAbility');if(ability)ability.textContent=m.abilityName}const img=$('enemyImage');if(img&&m&&m.image&&img.getAttribute('src')!==m.image)img.src=m.image;if($('enemyEmoji'))$('enemyEmoji').textContent='';if($('enemyFace'))$('enemyFace').textContent='';if($('battleBackground')&&!state.background)$('battleBackground').style.backgroundImage=`url("${BACKGROUNDS[Math.floor(Math.random()*BACKGROUNDS.length)]}")';
 const pc=state.playerFantasy||FANTASY_CHARACTERS[0];const pi=$('playerFantasyImage');if(pi){const u=ASSET_BASE+'fantasy/'+pc.stand;if(!pi.src||!pi.src.includes(pc.stand))pi.src=u}const pn=$('playerFantasyName');if(pn)pn.textContent=pc.name;const pns=$('playerFantasyNameScene');if(pns)pns.textContent=pc.name;
}
function reset(){clearInterval(timerId);CORE=state?.nextCore||30;const oldChar=state?.playerFantasy;state={deck:makeDeck(),discard:[],hand:[],selected:[],operators:[],playerHP:MAX_HP,enemyHP:MAX_HP,changeUsed:false,gameOver:false,phase:'player',catchMode:false,nextCore:null,playerGuard:0,enemyGuard:0,corePower:false,combo:0,bestCombo:0,strategy:'near',turns:0,monster:{...monsterForCore(CORE)},playerFantasy:oldChar||FANTASY_CHARACTERS[Math.floor(Math.random()*FANTASY_CHARACTERS.length)],background:BACKGROUNDS[Math.floor(Math.random()*BACKGROUNDS.length)]};$('overlay').classList.add('hidden');$('executeBtn').textContent='⚡ コマンド発動！';draw(HAND_SIZE);log(`バトル開始！ ${state.monster.name}（コア${CORE}）`);status(`あなたのターン！ ${CORE}を中心に、ねらった数字を作ろう。`);render();startTimer()}
function draw(n){for(let i=0;i<n;i++){if(!state.deck.length){state.deck=shuffle(state.discard);state.discard=[]}if(state.deck.length)state.hand.push(state.deck.pop())}}
function findCommand(v){return getRanges().find(r=>v>=r.min&&v<=r.max)}
function render(){if(!state)return;ensureEnhancementUI();$('coreNumber').textContent=CORE;$('enemyHpText').textContent=`HP ${state.enemyHP} / ${MAX_HP}`;$('playerHpText').textContent=`HP ${state.playerHP} / ${MAX_HP}`;$('enemyHpBar').style.width=`${Math.max(0,state.enemyHP/MAX_HP*100)}%`;$('playerHpBar').style.width=`${Math.max(0,state.playerHP/MAX_HP*100)}%`;$('handCount').textContent=`(${state.hand.length}枚)`;$('hand').innerHTML='';state.hand.forEach((n,i)=>{const b=document.createElement('button');b.className='number-card'+(state.selected.includes(i)?' selected':'');b.textContent=n;b.setAttribute('aria-label',`数字 ${n}`);b.onclick=()=>toggleCard(i);$('hand').appendChild(b)});const rs=getRanges();$('commandCards').innerHTML=rs.map(r=>`<div class="command ${r.just?'just':''}"><strong>${r.icon} ${r.name}</strong><small>${r.min===r.max?r.min:`${r.min}〜${r.max}`}</small></div>`).join('');renderDistanceTrack();$('coreSelect').value=String(CORE);$('changeBtn').disabled=state.changeUsed||state.gameOver||state.phase!=='player'||state.catchMode;updateExpression();syncEnhancements()}
function renderDistanceTrack(){const box=$('rangeGuide');if(!box)return;let html=`<span class="distance-core">CORE ${CORE}</span>`;for(let d=-10;d<=10;d++){if(d===0){html+='<span class="distance-cell just">0</span>';continue}const cls=Math.abs(d)<=3?'hot':Math.abs(d)<=6?'mid':'far';html+=`<span class="distance-cell ${cls}">${d>0?'+':''}${d}</span>`}box.innerHTML=html}
function toggleCard(i){if(state.gameOver||state.phase!=='player')return;const p=state.selected.indexOf(i);if(p>=0)state.selected.splice(p,1);else if(state.selected.length<MAX_CARDS_PER_MOVE)state.selected.push(i);state.operators=state.operators.slice(0,Math.max(0,state.selected.length-1));updateExpression();render()}
function evaluate(nums,ops){if(nums.length<2||ops.length!==nums.length-1)return null;let value=nums[0];for(let i=0;i<ops.length;i++){const n=nums[i+1],op=ops[i];if(op==='+')value+=n;else if(op==='-')value-=n;else if(op==='*')value*=n;else if(op==='/'){if(n===0)return null;value/=n}if(!Number.isInteger(value)||value<0||value>1000)return null}return value}
function calc(){if(state.selected.length<2)return null;const nums=state.selected.map(i=>state.hand[i]);const value=evaluate(nums,state.operators);return value===null?null:{nums,value,ops:[...state.operators]}}
function chooseOperator(op){if(state.gameOver||state.phase!=='player'||!state.monster.ops.includes(op))return;if(state.selected.length<2)return;if(state.operators.length>=state.selected.length-1)return;if(state.operators.length&&state.operators[state.operators.length-1]===op){status('3枚の計算では、同じ演算子を連続して使えません。');return}state.operators.push(op);updateExpression();render()}
function updateExpression(){if(!state)return;const nums=state.selected.map(i=>state.hand[i]);let text=nums.length?String(nums[0]):'数字を2〜3枚選択してください';for(let i=0;i<state.operators.length;i++)text+=` ${state.operators[i]} ${nums[i+1]??'?'}`;$('expression').textContent=text+(nums.length>=2&&state.operators.length===nums.length-1?' ＝ ?':'');const c=calc();if(!c)$('numberDistance').textContent='計算式を完成させよう';else if(c.value===CORE)$('numberDistance').textContent='🌟 JUST！ コアナンバーぴったり！';else $('numberDistance').textContent=`COREまで ${Math.abs(CORE-c.value)} ${c.value<CORE?'小さい':'大きい'}`;$('executeBtn').disabled=!c||!findCommand(c.value)||state.gameOver||state.phase!=='player';$('operatorHint').textContent=state.monster.ops.length<4?`このモンスターは ${state.monster.ops.join('・')} を使います`:(nums.length===3?'3枚：演算子を2つ選択（同じ演算子の連続使用は不可）':'2枚：演算子を1つ選択')}
function startTimer(){clearInterval(timerId);state.time=state.catchMode?CATCH_TIME:TURN_TIME;$('timer').textContent=state.time;if(state.phase!=='player')return;timerId=setInterval(()=>{if(state.gameOver||state.phase!=='player'){clearInterval(timerId);return}state.time--;$('timer').textContent=state.time;if(state.time<=0){clearInterval(timerId);if(state.catchMode){catchMiss();return}status('⏰ 時間切れ！ ターン終了。');log('あなた：時間切れでターン終了');state.selected=[];state.operators=[];state.phase='cpu';render();setTimeout(cpuTurn,600)}},1000)}
function playerExecute(){if(state.catchMode){catchExecute();return}const c=calc(),cmd=c&&findCommand(c.value);if(!c||!cmd)return;clearInterval(timerId);const used=state.selected.map(i=>state.hand[i]);rememberMethod(c);const just=c.value===CORE;const prev=state.combo||0;state.combo=just?prev+1:0;state.bestCombo=Math.max(state.bestCombo,state.combo);[...state.selected].sort((a,b)=>b-a).forEach(i=>state.hand.splice(i,1));state.discard.push(...used);state.selected=[];state.operators=[];applyPlayerCommand(cmd,c.value);if(state.enemyHP<=0){finishWin();return}draw(HAND_SIZE-state.hand.length);state.changeUsed=false;state.phase='cpu';render();setTimeout(cpuTurn,850)}
function applyPlayerCommand(cmd,value){const just=value===CORE;let text=`あなた：${value} → ${cmd.icon}${cmd.name}`;let d=0;if(cmd.name==='攻撃')d=1;if(cmd.name==='強攻撃')d=2;if(state.corePower&&d){d*=3;state.corePower=false;text+=' ⚡CORE POWER！'}if(d){state.enemyHP=Math.max(0,state.enemyHP-d);text+=`（${d}ダメージ）`}else if(cmd.name==='防御'){state.playerGuard=state.monster.ability==='guard'?2:1;text+='（次の攻撃を軽減）'}else if(cmd.name==='回復'){const before=state.playerHP;state.playerHP=Math.min(MAX_HP,state.playerHP+3);text+=`（HP ${state.playerHP-before}回復）`}if(just){state.corePower=true;if(state.monster.ability==='eater')state.playerHP=Math.min(MAX_HP,state.playerHP+1);text+=` 🌟 JUST！ ${state.combo>=2?`JUST COMBO ${state.combo}！`:''} 次の攻撃×3！`}if(state.monster.ability==='breath'&&just)text+=' もふウルフのブレスが強化される！';log(text);status(text)}
function cpuTurn(){if(state.gameOver)return;state.phase='cpu';$('enemyThought').textContent='CPUが数字を考えています…';$('enemyFormula').textContent='……';$('enemyCommand').textContent='';render();setTimeout(()=>{const choice=cpuChoose();if(!choice){$('enemyThought').textContent='CPUはカードをチェンジ！';$('enemyFormula').textContent='OUT';$('enemyCommand').textContent='カードを1枚交換';log('CPU：コマンドを作れずカードを1枚交換');draw(1);finishCpuTurn();return}const{indices,ops,value,cmd,reason}=choice;const nums=indices.map(i=>state.hand[i]);$('enemyThought').textContent=reason;$('enemyFormula').textContent=buildFormula(nums,ops,value);$('enemyCommand').textContent=`${cmd.icon} ${cmd.name}${value===CORE?'　🌟 JUST！':''}`;render();setTimeout(()=>{[...indices].sort((a,b)=>b-a).forEach(i=>state.hand.splice(i,1));state.discard.push(...nums);applyCpuCommand(cmd,value);log(`CPU：${buildFormula(nums,ops,value)} → ${cmd.icon}${cmd.name}${value===CORE?' 🌟 JUST！':''}`);if(state.playerHP<=0){finishLose();return}draw(HAND_SIZE-state.hand.length);state.changeUsed=false;finishCpuTurn()},850)},700)}
function buildFormula(nums,ops,value){let s=String(nums[0]);for(let i=0;i<ops.length;i++)s+=` ${ops[i]} ${nums[i+1]}`;return`${s} ＝ ${value}`}
function applyCpuCommand(cmd,value){let d=cmd.name==='攻撃'?1:cmd.name==='強攻撃'?2:0;if(cmd.name==='防御'){state.enemyGuard=state.monster.ability==='guard'?2:1;return}if(cmd.name==='回復'){state.enemyHP=Math.min(MAX_HP,state.enemyHP+3);return}if(value===CORE){d=1;state.enemyCorePower=true}if(state.enemyCorePower&&d){d*=3;state.enemyCorePower=false}if(state.enemyGuard&&d){d=Math.max(0,d-(state.enemyGuard===2?d:1));state.enemyGuard=0}if(state.playerGuard&&d){d=state.playerGuard===2?Math.ceil(d/2):0;state.playerGuard=0}state.playerHP=Math.max(0,state.playerHP-d)}
function cpuChoose(){const candidates=[],h=state.hand,ops=state.monster.ops;for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(const op of ops){const value=evaluate([h[i],h[j]],[op]);if(value!==null){const cmd=findCommand(value);if(cmd)candidates.push({indices:[i,j],ops:[op],value,cmd})}}for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(let k=j+1;k<h.length;k++)for(const op1 of ops)for(const op2 of ops){if(op1===op2)continue;const value=evaluate([h[i],h[j],h[k]],[op1,op2]);if(value!==null){const cmd=findCommand(value);if(cmd)candidates.push({indices:[i,j,k],ops:[op1,op2],value,cmd})}}if(!candidates.length)return null;const just=candidates.filter(x=>x.value===CORE),strong=candidates.filter(x=>x.cmd.name==='強攻撃');let choice;if(state.monster.personality==='かんたん')choice=candidates[Math.floor(Math.random()*candidates.length)];else if((state.monster.personality==='てんさい'||state.playerHP<=2||state.monster.ability==='just')&&just.length)choice=just[Math.floor(Math.random()*just.length)];else if(state.enemyHP<=3&&strong.length)choice=strong[Math.floor(Math.random()*strong.length)];else if(state.monster.ability==='breath')choice=candidates.slice().sort((a,b)=>Math.abs(b.value-CORE)-Math.abs(a.value-CORE))[0];else choice=candidates.slice().sort((a,b)=>Math.abs(a.value-CORE)-Math.abs(b.value))[0];choice.reason=choice.value===CORE?'🌟 JUSTをねらった！':`🧠 ${CORE}との差 ${Math.abs(CORE-choice.value)} を選んだ`;return choice}
function changeCard(){if(state.changeUsed||state.gameOver||state.phase!=='player')return;const idx=state.selected[0]??0;if(state.hand[idx]===undefined)return;state.discard.push(state.hand.splice(idx,1)[0]);draw(1);state.selected=[];state.operators=[];state.changeUsed=true;state.time=Math.max(5,state.time-3);log('チェンジ！ 時間を3秒使って手札を交換。');status('カードチェンジ！ 残り時間に注意！');render()}
function finishCpuTurn(){state.phase='player';state.selected=[];state.operators=[];$('enemyThought').textContent='あなたのターン！';render();status(`あなたのターン！ ${CORE}を中心に、ねらった数字を作ろう。`);startTimer()}
function finishWin(){clearInterval(timerId);state.gameOver=true;render();status('勝利！ モンスターを倒した！');setTimeout(catchChance,650)}
function finishLose(){clearInterval(timerId);state.gameOver=true;render();showResult('敗北…','😵','数字の作り方を変えて、もう一度挑戦しよう！',`ベストJUST COMBO：${state.bestCombo}`)}
function catchChance(){state.catchMode=true;state.gameOver=false;state.phase='player';state.selected=[];state.operators=[];state.combo=0;state.hand=[];state.deck=makeDeck();draw(HAND_SIZE);render();status(`ゲットチャンス！ ${CORE} JUSTを作れ！`);$('executeBtn').textContent='GETする！';$('changeBtn').disabled=true;$('enemyThought').textContent='モンスターが逃げる前に捕まえよう！';$('enemyFormula').textContent=`${CORE} JUST をねらえ！`;$('enemyCommand').textContent='ピッタリなら GET！';startTimer()}
function catchExecute(){const c=calc();if(!c)return;rememberMethod(c);if(c.value===CORE){clearInterval(timerId);state.catchMode=false;state.gameOver=true;addMonster(state.monster);showResult('ゲット！','🎉',`${CORE} JUST！ ${state.monster.name}を仲間にした！`,`${getCollection().length} / ${MONSTERS.length} 体を発見`)}else{clearInterval(timerId);catchMiss(`${c.value} だった！`)}}
function catchMiss(reason='時間切れ！'){state.catchMode=false;state.gameOver=true;showResult('逃げられた！','💨',`${reason} コアナンバー${CORE}にピッタリ届かなかった…`,`発見図鑑：${getDiscovery().length}通り`)}
function showResult(title,emoji,text,extra=''){ $('resultTitle').textContent=title;$('resultEmoji').textContent=emoji;$('resultText').textContent=text;$('resultExtra').textContent=extra;$('overlay').classList.remove('hidden') }
function log(t){const el=$('log');if(!el)return;const p=document.createElement('p');p.textContent=t;el.prepend(p);while(el.children.length>18)el.lastChild.remove()}
function status(t){if($('statusMessage'))$('statusMessage').textContent=t}
function bindUI(){document.querySelectorAll('#operators button').forEach(b=>b.onclick=()=>chooseOperator(b.dataset.op));$('restartBtn').onclick=()=>reset();$('nextBtn').onclick=()=>reset();$('coreSelect').onchange=()=>{const c=Number($('coreSelect').value);if(!CORES.includes(c))return;state={...(state||{}),nextCore:c};reset()};$('executeBtn').onclick=()=>playerExecute();$('changeBtn').onclick=()=>changeCard()}
function animateHero(kind){const img=$('playerFantasyImage'),c=state.playerFantasy;if(!img||!c)return;img.src=ASSET_BASE+'fantasy/'+(kind==='special'?c.special:c.attack);img.classList.remove('battle-attack','battle-special');void img.offsetWidth;img.classList.add(kind==='special'?'battle-special':'battle-attack');setTimeout(()=>{img.src=ASSET_BASE+'fantasy/'+c.stand;img.classList.remove('battle-attack','battle-special')},750)}
function hookAnimations(){const old=playerExecute;playerExecute=function(){const before=state?.enemyHP||0;const c=calc();old();if(c&&state){animateHero(c.value===CORE?'special':'attack');if((before-state.enemyHP)>0){const e=$('enemyImage');if(e){e.classList.remove(c.value===CORE?'battle-special':'battle-damage');void e.offsetWidth;e.classList.add(c.value===CORE?'battle-special':'battle-damage');setTimeout(()=>e.classList.remove('battle-special','battle-damage'),900)}}}}}
window.addEventListener('load',()=>{bindUI();hookAnimations();reset()});