const MAX_HP=10,HAND_SIZE=5,MAX_CARDS_PER_MOVE=3,TURN_TIME=20,CATCH_TIME=15;
const CORES=[20,30,50,100];let CORE=30;
const MONSTERS=[
{name:'ぷるんスライム',core:20,personality:'かんたん',abilityName:'ぷるぷるガード',ability:'guard',ops:['+','-'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/purun-little-magic-slime.webp'},
{name:'こもりんバット',core:30,personality:'ふつう',abilityName:'JUSTハンター',ability:'just',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/komorin-little-night-bat.webp'},
{name:'もふウルフ',core:50,personality:'てんさい',abilityName:'ブレス',ability:'breath',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/mofu-wolf-frost-pup.webp'},
{name:'プリズムテールドレイク',core:100,personality:'てんさい',abilityName:'コアイーター',ability:'eater',ops:['+','-','*','/'],image:'https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/prism-tail-drake.webp'}];
const CHARS=[['かい・魔導士','kai-mage.png','kai-mage-attack.png','kai-mage-special.png'],['そら・剣士','sora-swordsman.png','sora-swordsman-attack.png','sora-swordsman-special.png'],['りく・忍者','riku-ninja.png','riku-ninja-attack.png','riku-ninja-special.png'],['つき・アーチャー','tsuki-archer.png','tsuki-archer-attack.png','tsuki-archer-special.png'],['なみ・守護騎士','nami-guardian-knight.png','nami-knight-attack.png','nami-knight-special.png'],['さく・僧侶','saku-cleric-healer.png','saku-cleric-attack.png','saku-cleric-special.png']].map(x=>({name:x[0],stand:x[1],attack:x[2],special:x[3]}));
const BASE='https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/';
const BG=['forest.webp','cave.webp','ruins.webp'].map(x=>BASE+'fantasy/backgrounds/'+x);let state,timerId;
const $=id=>document.getElementById(id);const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function monsterForCore(c){return MONSTERS.find(m=>m.core===c)||MONSTERS[1]}
function ranges(){const c=CORE;return[{min:c-10,max:c-7,name:'防御',icon:'🛡️'},{min:c-6,max:c-4,name:'攻撃',icon:'⚔️'},{min:c-3,max:c-1,name:'強攻撃',icon:'💥'},{min:c,max:c,name:'JUST',icon:'🌟',just:true},{min:c+1,max:c+3,name:'強攻撃',icon:'💥'},{min:c+4,max:c+6,name:'攻撃',icon:'⚔️'},{min:c+7,max:c+10,name:'回復',icon:'💚'}]}
function makeDeck(){const a=[];for(let n=1;n<=20;n++)for(let i=0;i<2;i++)a.push(n);return shuffle(a)}
function collection(){try{return JSON.parse(localStorage.getItem('numberCoreMonsters')||'[]')}catch{return[]}}
function addMonster(m){const a=collection();if(!a.includes(m.name)){a.push(m.name);localStorage.setItem('numberCoreMonsters',JSON.stringify(a))}}
function discovery(){try{return JSON.parse(localStorage.getItem('numberCoreDiscovery')||'[]')}catch{return[]}}
function remember(c){if(!c)return;const key=`${c.nums.join(',')}|${c.ops.join(',')}|${c.value}`;const a=discovery();if(!a.some(x=>x.key===key)){a.push({key,nums:c.nums,ops:c.ops,value:c.value,core:CORE,at:Date.now()});localStorage.setItem('numberCoreDiscovery',JSON.stringify(a))}}
function formula(c){if(!c)return'';let s=String(c.nums[0]);for(let i=0;i<c.ops.length;i++)s+=` ${c.ops[i]} ${c.nums[i+1]}`;return`${s} ＝ ${c.value}`}
function textStrategy(){return state.strategy==='just'?'JUSTを作れる組み合わせを優先しよう。':state.strategy==='near'?`${CORE}との差を小さくする組み合わせを探そう。`:'まずは防御・攻撃で安定して戦おう。'}
function setupExtra(){const calc=document.querySelector('.calculator'),battle=document.querySelector('.battle');if(calc&&!$('strategyPanel')){const d=document.createElement('div');d.id='strategyPanel';d.className='strategy-panel';d.innerHTML='<div class="section-title">今回の作戦</div><div class="strategy-buttons"><button data-s="just">🌟 JUSTをねらう</button><button data-s="near">🎯 できるだけ近づく</button><button data-s="safe">🛡️ 安全に戦う</button></div><div id="strategyText" class="strategy-text"></div>';calc.insertBefore(d,calc.querySelector('.expression'));d.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{state.strategy=b.dataset.s;render();status(textStrategy())})}if(battle&&!$('comboHud')){const d=document.createElement('div');d.id='comboHud';d.className='combo-hud';d.innerHTML='<span>JUST COMBO</span><b id="comboCount">0</b><small id="powerState">CORE POWER 準備中</small>';battle.appendChild(d)}}
function sync(){if(!state)return;setupExtra();if($('discoveryCount'))$('discoveryCount').textContent=discovery().length;if($('comboCount'))$('comboCount').textContent=state.combo||0;if($('powerState'))$('powerState').textContent=state.corePower?'⚡ CORE POWER READY':'CORE POWER '+(state.combo>=2?'チャージ中':'準備中');if($('strategyText'))$('strategyText').textContent=textStrategy();const m=state.monster;if(m){if($('enemyNameSide'))$('enemyNameSide').textContent=m.name;if($('enemyCoreSide'))$('enemyCoreSide').textContent=CORE;if($('cpuPersonality'))$('cpuPersonality').textContent=m.personality;if($('enemyAbility'))$('enemyAbility').textContent=m.abilityName;if($('enemyName'))$('enemyName').textContent=m.name}const ei=$('enemyImage');if(ei&&m&&ei.getAttribute('src')!==m.image)ei.src=m.image;if($('enemyEmoji'))$('enemyEmoji').textContent='';if($('enemyFace'))$('enemyFace').textContent='';const bg=$('battleBackground');if(bg&&state.background)bg.style.backgroundImage=`url("${state.background}")`;const c=state.playerFantasy||CHARS[0],pi=$('playerFantasyImage');if(pi){const u=BASE+'fantasy/'+c.stand;if(!pi.src.includes(c.stand))pi.src=u}if($('playerFantasyName'))$('playerFantasyName').textContent=c.name;if($('playerFantasyNameScene'))$('playerFantasyNameScene').textContent=c.name)}
function reset(){clearInterval(timerId);CORE=state?.nextCore||30;const char=state?.playerFantasy;state={deck:makeDeck(),discard:[],hand:[],selected:[],operators:[],playerHP:MAX_HP,enemyHP:MAX_HP,changeUsed:false,gameOver:false,phase:'player',catchMode:false,nextCore:null,playerGuard:0,enemyGuard:0,corePower:false,enemyCorePower:false,combo:0,bestCombo:0,strategy:'near',turns:0,monster:{...monsterForCore(CORE)},playerFantasy:char||CHARS[Math.floor(Math.random()*CHARS.length)],background:BG[Math.floor(Math.random()*BG.length)]};$('overlay').classList.add('hidden');$('executeBtn').textContent='⚡ コマンド発動！';draw(5);log(`バトル開始！ ${state.monster.name}（コア${CORE}）`);status(`あなたのターン！ ${CORE}を中心に、ねらった数字を作ろう。`);render();startTimer()}
function draw(n){for(let i=0;i<n;i++){if(!state.deck.length){state.deck=shuffle(state.discard);state.discard=[]}if(state.deck.length)state.hand.push(state.deck.pop())}}
function findCommand(v){return ranges().find(r=>v>=r.min&&v<=r.max)}
function render(){if(!state)return;const rs=ranges();$('coreNumber').textContent=CORE;$('enemyHpText').textContent=`HP ${state.enemyHP} / ${MAX_HP}`;$('playerHpText').textContent=`HP ${state.playerHP} / ${MAX_HP}`;$('enemyHpBar').style.width=`${state.enemyHP/MAX_HP*100}%`;$('playerHpBar').style.width=`${state.playerHP/MAX_HP*100}%`;$('handCount').textContent=`(${state.hand.length}枚)`;$('hand').innerHTML='';state.hand.forEach((n,i)=>{const b=document.createElement('button');b.className='number-card'+(state.selected.includes(i)?' selected':'');b.textContent=n;b.onclick=()=>toggleCard(i);$('hand').appendChild(b)});$('commandCards').innerHTML=rs.map(r=>`<div class="command ${r.just?'just':''}"><strong>${r.icon} ${r.name}</strong><small>${r.min===r.max?r.min:`${r.min}〜${r.max}`}</small></div>`).join('');$('rangeGuide').innerHTML=`<span class="distance-core">CORE ${CORE}</span>`+Array.from({length:21},(_,i)=>i-10).map(d=>`<span class="distance-cell ${d===0?'just':Math.abs(d)<=3?'hot':Math.abs(d)<=6?'mid':'far'}">${d>0?'+':''}${d}</span>`).join('');$('changeBtn').disabled=state.changeUsed||state.gameOver||state.phase!=='player'||state.catchMode;$('coreSelect').value=String(CORE);updateExpression();sync()}
function toggleCard(i){if(state.gameOver||state.phase!=='player')return;const p=state.selected.indexOf(i);if(p>=0)state.selected.splice(p,1);else if(state.selected.length<3)state.selected.push(i);state.operators=state.operators.slice(0,Math.max(0,state.selected.length-1));updateExpression();render()}
function evaluate(nums,ops){if(nums.length<2||ops.length!==nums.length-1)return null;let v=nums[0];for(let i=0;i<ops.length;i++){const n=nums[i+1],op=ops[i];if(op==='+')v+=n;else if(op==='-')v-=n;else if(op==='*')v*=n;else if(op==='/'&&n!==0)v/=n;else return null;if(!Number.isInteger(v)||v<0||v>1000)return null}return v}
function calc(){if(state.selected.length<2)return null;const nums=state.selected.map(i=>state.hand[i]);const value=evaluate(nums,state.operators);return value===null?null:{nums,value,ops:[...state.operators]}}
function chooseOperator(op){if(state.gameOver||state.phase!=='player'||!state.monster.ops.includes(op)||state.selected.length<2)return;if(state.operators.length>=state.selected.length-1)return;if(state.operators.at(-1)===op){status('3枚では同じ演算子を続けて使えません。');return}state.operators.push(op);updateExpression();render()}
function updateExpression(){const nums=state.selected.map(i=>state.hand[i]);let s=nums.length?String(nums[0]):'数字を2〜3枚選択してください';for(let i=0;i<state.operators.length;i++)s+=` ${state.operators[i]} ${nums[i+1]??'?'}`;$('expression').textContent=s+(nums.length>=2&&state.operators.length===nums.length-1?' ＝ ?':'');const c=calc();$('numberDistance').textContent=!c?'計算式を完成させよう':c.value===CORE?'🌟 JUST！ コアナンバーぴったり！':`COREまで ${Math.abs(CORE-c.value)} ${c.value<CORE?'小さい':'大きい'}`;$('executeBtn').disabled=!c||!findCommand(c.value)||state.gameOver||state.phase!=='player';$('operatorHint').textContent=state.monster.ops.length<4?`このモンスターは ${state.monster.ops.join('・')} を使います`:nums.length===3?'3枚：演算子を2つ選択':'2枚：演算子を1つ選択'}
function startTimer(){clearInterval(timerId);state.time=state.catchMode?CATCH_TIME:Math.max(1,state.time||TURN_TIME);$('timer').textContent=state.time;if(state.phase!=='player')return;timerId=setInterval(()=>{if(state.gameOver||state.phase!=='player'){clearInterval(timerId);return}state.time--;$('timer').textContent=state.time;if(state.time<=0){clearInterval(timerId);if(state.catchMode)return catchMiss();state.selected=[];state.operators=[];state.phase='cpu';status('時間切れ！ CPUのターンへ。');render();setTimeout(cpuTurn,600)}},1000)}
function playerExecute(){if(state.catchMode)return catchExecute();const c=calc(),cmd=c&&findCommand(c.value);if(!c||!cmd)return;clearInterval(timerId);remember(c);const just=c.value===CORE;state.combo=just?state.combo+1:0;state.bestCombo=Math.max(state.bestCombo,state.combo);if(just)state.corePower=true;const used=state.selected.map(i=>state.hand[i]);[...state.selected].sort((a,b)=>b-a).forEach(i=>state.hand.splice(i,1));state.discard.push(...used);state.selected=[];state.operators=[];applyPlayerCommand(cmd,c.value);if(state.enemyHP<=0)return finishWin();draw(5-state.hand.length);state.changeUsed=false;state.phase='cpu';render();setTimeout(cpuTurn,850)}
function applyPlayerCommand(cmd,v){let d=cmd.name==='攻撃'?1:cmd.name==='強攻撃'?2:0;if(state.corePower&&d){d*=3;state.corePower=false}if(d){state.enemyHP=Math.max(0,state.enemyHP-d);log(`あなた：${v} → ${cmd.name}（${d}ダメージ）${v===CORE?' JUST！':''}`)}else if(cmd.name==='防御'){state.playerGuard=state.monster.ability==='guard'?2:1;log(`あなた：${v} → 防御（次の攻撃を軽減）`)}else if(cmd.name==='回復'){const before=state.playerHP;state.playerHP=Math.min(MAX_HP,state.playerHP+3);log(`あなた：${v} → 回復（HP +${state.playerHP-before}）`)}status(v===CORE?`JUST！ ${state.combo>=2?'JUST COMBO '+state.combo+'！ ':''}次の攻撃が強くなる！`:`${v} → ${cmd.name}`)}
function cpuCandidates(){const out=[],h=state.hand,ops=state.monster.ops;for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(const op of ops){const v=evaluate([h[i],h[j]],[op]);const cmd=findCommand(v);if(cmd)out.push({indices:[i,j],ops:[op],value:v,cmd})}for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(let k=j+1;k<h.length;k++)for(const a of ops)for(const b of ops){if(a===b)continue;const v=evaluate([h[i],h[j],h[k]],[a,b]),cmd=findCommand(v);if(cmd)out.push({indices:[i,j,k],ops:[a,b],value:v,cmd})}return out}
function cpuChoose(){const a=cpuCandidates();if(!a.length)return null;const just=a.filter(x=>x.value===CORE),strong=a.filter(x=>x.cmd.name==='強攻撃');let c;if(state.monster.personality==='かんたん')c=a[Math.floor(Math.random()*a.length)];else if((state.monster.personality==='てんさい'||state.playerHP<=2||state.monster.ability==='just')&&just.length)c=just[Math.floor(Math.random()*just.length)];else if(state.enemyHP<=3&&strong.length)c=strong[Math.floor(Math.random()*strong.length)];else c=a.sort((x,y)=>Math.abs(x.value-CORE)-Math.abs(y.value-CORE))[0];c.reason=c.value===CORE?'🌟 JUSTをねらった！':`🧠 ${CORE}との差 ${Math.abs(CORE-c.value)} を選んだ`;return c}
function cpuTurn(){if(state.gameOver)return;state.phase='cpu';$('enemyThought').textContent='CPUが数字を考えています…';$('enemyFormula').textContent='……';$('enemyCommand').textContent='';render();setTimeout(()=>{const c=cpuChoose();if(!c){draw(1);return finishCpuTurn()}const nums=c.indices.map(i=>state.hand[i]);$('enemyThought').textContent=c.reason;$('enemyFormula').textContent=formula({nums,ops:c.ops,value:c.value});$('enemyCommand').textContent=`${c.cmd.icon} ${c.cmd.name}${c.value===CORE?' JUST！':''}`;render();setTimeout(()=>{[...c.indices].sort((a,b)=>b-a).forEach(i=>state.hand.splice(i,1));state.discard.push(...nums);applyCpuCommand(c.cmd,c.value);if(state.playerHP<=0)return finishLose();draw(5-state.hand.length);finishCpuTurn()},850)},700)}
function applyCpuCommand(cmd,v){let d=cmd.name==='攻撃'?1:cmd.name==='強攻撃'?2:0;if(cmd.name==='防御'){state.enemyGuard=state.monster.ability==='guard'?2:1;return}if(cmd.name==='回復'){state.enemyHP=Math.min(MAX_HP,state.enemyHP+3);return}if(v===CORE){state.enemyCorePower=true;d=1}if(state.enemyCorePower&&d){d*=3;state.enemyCorePower=false}if(state.playerGuard&&d){d=state.playerGuard===2?Math.ceil(d/2):0;state.playerGuard=0}state.playerHP=Math.max(0,state.playerHP-d)}
function changeCard(){if(state.changeUsed||state.gameOver||state.phase!=='player')return;const i=state.selected[0]??0;if(state.hand[i]===undefined)return;state.discard.push(state.hand.splice(i,1)[0]);draw(1);state.selected=[];state.operators=[];state.changeUsed=true;state.time=Math.max(5,(state.time||TURN_TIME)-3);log('カードチェンジ！ 3秒を使った。');render()}
function finishCpuTurn(){state.phase='player';state.selected=[];state.operators=[];render();status(`あなたのターン！ ${CORE}を中心に、ねらった数字を作ろう。`);startTimer()}
function finishWin(){clearInterval(timerId);state.gameOver=true;render();status('勝利！ モンスターを倒した！');setTimeout(catchChance,600)}
function finishLose(){clearInterval(timerId);state.gameOver=true;showResult('敗北…','😵','数字の作り方を変えて、もう一度挑戦しよう！',`ベストJUST COMBO：${state.bestCombo}`)}
function catchChance(){state.catchMode=true;state.gameOver=false;state.phase='player';state.combo=0;state.selected=[];state.operators=[];state.hand=[];state.deck=makeDeck();draw(5);$('executeBtn').textContent='GETする！';render();status(`${CORE} JUSTを作ってモンスターを仲間にしよう！`);$('changeBtn').disabled=true;startTimer()}
function catchExecute(){const c=calc();if(!c)return;remember(c);if(c.value===CORE){clearInterval(timerId);state.catchMode=false;state.gameOver=true;addMonster(state.monster);showResult('ゲット！','🎉',`${CORE} JUST！ ${state.monster.name}を仲間にした！`,`${collection().length} / ${MONSTERS.length} 体を発見`)}else catchMiss(`${c.value} だった！`)}
function catchMiss(reason='時間切れ！'){clearInterval(timerId);state.catchMode=false;state.gameOver=true;showResult('逃げられた！','💨',`${reason} コアナンバーにピッタリ届かなかった…`,`発見図鑑：${discovery().length}通り`)}
function showResult(t,e,txt,extra=''){if($('resultTitle'))$('resultTitle').textContent=t;if($('resultEmoji'))$('resultEmoji').textContent=e;if($('resultText'))$('resultText').textContent=txt;if($('resultExtra'))$('resultExtra').textContent=extra;$('overlay').classList.remove('hidden')}
function log(t){const el=$('log');if(!el)return;const p=document.createElement('p');p.textContent=t;el.prepend(p);while(el.children.length>18)el.lastChild.remove()}
function status(t){if($('statusMessage'))$('statusMessage').textContent=t}
function animateHero(kind){const c=state.playerFantasy,img=$('playerFantasyImage');if(!c||!img)return;img.src=BASE+'fantasy/'+(kind==='special'?c.special:c.attack);img.classList.remove('battle-attack','battle-special');void img.offsetWidth;img.classList.add(kind==='special'?'battle-special':'battle-attack');setTimeout(()=>{img.src=BASE+'fantasy/'+c.stand;img.classList.remove('battle-attack','battle-special')},750)}
function bind(){document.querySelectorAll('#operators button').forEach(b=>b.onclick=()=>chooseOperator(b.dataset.op));$('restartBtn').onclick=reset;$('nextBtn').onclick=reset;$('executeBtn').onclick=playerExecute;$('changeBtn').onclick=changeCard;$('coreSelect').onchange=()=>{state={...(state||{}),nextCore:Number($('coreSelect').value)};reset()}}
window.addEventListener('load',()=>{bind();reset()});